### ISSUE TITLE
PayPal PostSale not processing

### ISSUE THREAD

**Issue by richardhj** [richardhj/isotope-klarna-checkout#2]
When choosing an external payment method which is of type "PayPal Standard Checkout", the error `PayPal IPN: manipulation in payment from "…" !` occurs in the system log. Orders get not processed.

No solution but disabling the security feature in the `processPostsale()` available yet.

**Comment by richardhj** [comment]
The error message (stated above) is a security feature in order to prohibit PayPal payments unequal to to the actual order amount.

The implementation can be found here in the Isotope core: https://github.com/isotope/core/blob/2.5.1/system/modules/isotope/library/Isotope/Model/Payment/Paypal.php#L61

However, in order to investigate this issue, I'd disabled this feature and replaced it with the following snippet:
```php
        // Validate payment data (see #2221)
        if ($objOrder->getCurrency() !== \Input::post('mc_currency')
            || $objOrder->getTotal() != \Input::post('mc_gross')
        ) {
          \System::log('PayPal IPN: manipulation in payment from "' . \Input::post('payer_email') . '" !', __METHOD__, TL_ERROR);
            \System::log('…'.$objOrder->getTotal().$objOrder->getCurrency().' != '.\Input::post('mc_gross').\Input::post('mc_currency'), __METHOD__, TL_ERROR);
            //return;
        }
```

I was pretty sure, that I'm going to get to know the issue. In case the if-condition fails, I would know the reason…

![screen shot 2018-05-02 at 10 04 43](https://user-images.githubusercontent.com/1284725/39512197-52455900-4df0-11e8-8fd6-28dc4311175e.png)

Sometimes there is no problems (see 21.04. and 26.04.) and in case there is a problem, both the order amount and currency seem to be correct 😳

(I guess the currency check `'EUR' !== 'EUR'` fails. Maybe there is a hidden line break or somewhat)

**Comment by richardhj** [comment]
@aschempp Do you have any thoughts to share on this one? (sorry for pinging 🙈)

**Comment by aschempp** [comment]
I don't get how this PayPal problem is related to this Klarna extension?

I rather think it's a float issue than a hidden character in the currency, have you tried converting and rounding the total to a string?

**Comment by fritzmg** [comment]
@aschempp this extension replaces the Isotope checkout module and allows other external payment providers (like PayPal).

@richardhj why is it done this way? Why not simply add klarna as a regular payment provider within Isotope? (on that note: is klarna different from sofortüberweisung?)

**Comment by richardhj** [comment]
> @richardhj why is it done this way? Why not simply add klarna as a regular payment provider within Isotope? (on that note: is klarna different from sofortüberweisung?)

The Klarna checkout includes an iFrame on the checkout site, the Klarna Checkout then collects the shipping and billing address, the shipping and payment method. Its an *entire* checkout. That's why this extension provides a new module.  
Demo: https://kcotest.henkenjohann.me/kasse.html?config=6

And after latest investigation, there truly are some rounding errors, as @aschempp mentioned.

![screen shot 2018-05-12 at 12 42 38](https://user-images.githubusercontent.com/1284725/39956530-e2063984-55e2-11e8-98e6-e05f9a34f03b.png)

It's not the first time me having float issues (see ca4ecf95bee6f420b9297911f8ca357b7f5ecc37), maybe I have to read some literature as I don't know what the reason is for float issues 😸

Thanks folks!

**Comment by richardhj** [comment]
Addendum:  
Klarna has to products:
Klarna Payments and the Klarna Checkout. You are able to implement the Klarna Payment products as payment method, i.e. Sofortüberweisung. However the Klarna Checkout cannot be implemented as payment method as it replaces the native checkout @fritzmg.

**Comment by fritzmg** [comment]
Oh I see, thx for the clarification :)
