### ISSUE TITLE
Shipping Methods don't get updated by changing customer's cart

### ISSUE THREAD

**Issue by janoschbatschi** [richardhj/isotope-klarna-checkout#8]
Following situation: 
- Producttype "freeproduct" qualifies for free shipping
- Producttype "product" has shipping costs of 10€

If the cart has "freeproduct" in it, proceed to checkout Klarna only offers free shipping. So far so good. Now if I delete the "freeproduct" and add "product" to the cart, proceed to checkout, Klarna still offers free shipping.

After clearing the cookies: if the cart only has "product" in it, Klarna offers only shipping costs.

**Comment by richardhj** [comment]
Please check the logs in the Klarna interface and try to troubleshoot by looking into the requests made by the Isotope e-commerce. If you find some indicators, we can work on a fix.

**Comment by janoschbatschi** [comment]
Looking at the Klara Log, all requests seem to be correct. What I just found out is, whenever there is an address-update request, the shipping options become updated correctly. 

So a fix could be to perform an address-update whenever the cart changes? Would this be a practical/correct way to do that?

**Comment by richardhj** [comment]
Please check if the latest release is fixing your issue.

**Comment by janoschbatschi** [comment]
Yes! 1.0.4 fixed this issue - thank you!
